# /etc/pacman.conf for Rimuru OS

[options]
Color
ILoveCandy
VerbosePkgLists
HoldPkg = pacman glibc
Architecture = auto
CheckSpace
ParallelDownloads = 5
DownloadUser = alpm
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

# Rimuru Custom System Repository
[rimuru]
SigLevel = Optional TrustAll
Server = https://repo.rimuru-os.org/$arch
Server = file:///var/cache/rimuru/repo

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
