# pacman.conf for building Rimuru OS with mkarchiso

[options]
HoldPkg     = pacman glibc
Architecture = auto
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# Rimuru Local Custom Repository (used during build for custom packages)
[rimuru]
SigLevel = Optional TrustAll
Server = file:///var/tmp/rimuru-repo

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
